--Add Location
EXEC AddLocation @Zipcode = '695001', @Name = 'Thiruvananthapuram';
EXEC AddLocation @Zipcode = '682001', @Name = 'Kochi (Cochin)';
EXEC AddLocation @Zipcode = '673001', @Name = 'Kozhikode (Calicut)';
EXEC AddLocation @Zipcode = '680001', @Name = 'Thrissur';
EXEC AddLocation @Zipcode = '670001', @Name = 'Kannur';
EXEC AddLocation @Zipcode = '691001', @Name = 'Kollam (Quilon)';
EXEC AddLocation @Zipcode = '688001', @Name = 'Alappuzha (Alleppey)';
EXEC AddLocation @Zipcode = '678001', @Name = 'Palakkad (Palghat)';
EXEC AddLocation @Zipcode = '676505', @Name = 'Malappuram';
EXEC AddLocation @Zipcode = '689645', @Name = 'Pathanamthitta';
EXEC AddLocation @Zipcode = '671121', @Name = 'Kasaragod';
EXEC AddLocation @Zipcode = '686001', @Name = 'Kottayam';
EXEC AddLocation @Zipcode = '685602', @Name = 'Idukki';
EXEC AddLocation @Zipcode = '673121', @Name = 'Wayanad';
EXEC AddLocation @Zipcode = '682011', @Name = 'Ernakulam';
EXEC AddLocation @Zipcode = '670101', @Name = 'Thalassery';
EXEC AddLocation @Zipcode = '686661', @Name = 'Muvattupuzha';
EXEC AddLocation @Zipcode = '683101', @Name = 'Aluva';
EXEC AddLocation @Zipcode = '691523', @Name = 'Adoor';
EXEC AddLocation @Zipcode = '695541', @Name = 'Nedumangad';
EXEC AddLocation @Zipcode = '695141', @Name = 'Varkala';
EXEC AddLocation @Zipcode = '680101', @Name = 'Guruvayur';
EXEC AddLocation @Zipcode = '679322', @Name = 'Perinthalmanna';
EXEC AddLocation @Zipcode = '682002', @Name = 'Mattancherry';
EXEC AddLocation @Zipcode = '670307', @Name = 'Payyannur';
EXEC AddLocation @Zipcode = '685584', @Name = 'Thodupuzha';
EXEC AddLocation @Zipcode = '680121', @Name = 'Irinjalakuda';
EXEC AddLocation @Zipcode = '671314', @Name = 'Nileshwaram';
EXEC AddLocation @Zipcode = '686575', @Name = 'Pala';
EXEC AddLocation @Zipcode = '680307', @Name = 'Chalakudy';
EXEC AddLocation @Zipcode = '686101', @Name = 'Changanassery';
EXEC AddLocation @Zipcode = '676101', @Name = 'Tirur';
EXEC AddLocation @Zipcode = '686691', @Name = 'Kothamangalam';
EXEC AddLocation @Zipcode = '670567', @Name = 'Kannur University';
EXEC AddLocation @Zipcode = '680506', @Name = 'Chavakkad';
EXEC AddLocation @Zipcode = '685612', @Name = 'Munnar';
EXEC AddLocation @Zipcode = '688524', @Name = 'Cherthala';
EXEC AddLocation @Zipcode = '683542', @Name = 'Perumbavoor';
EXEC AddLocation @Zipcode = '695101', @Name = 'Attingal';
EXEC AddLocation @Zipcode = '670141', @Name = 'Taliparamba';
EXEC AddLocation @Zipcode = '679122', @Name = 'Shoranur';
EXEC AddLocation @Zipcode = '678101', @Name = 'Chittur';
EXEC AddLocation @Zipcode = '686575', @Name = 'Palai';
EXEC AddLocation @Zipcode = '679101', @Name = 'Ottappalam';
EXEC AddLocation @Zipcode = '690101', @Name = 'Mavelikara';
EXEC AddLocation @Zipcode = '676121', @Name = 'Manjeri';
EXEC AddLocation @Zipcode = '689101', @Name = 'Thiruvalla';
EXEC AddLocation @Zipcode = '679577', @Name = 'Ponnani';
EXEC AddLocation @Zipcode = '682021', @Name = 'Thrikkakara';
EXEC AddLocation @Zipcode = '690502', @Name = 'Kayamkulam';
EXEC AddLocation @Zipcode = '686673', @Name = 'Muvattupuzha';
EXEC AddLocation @Zipcode = '673101', @Name = 'Vadakara';
EXEC AddLocation @Zipcode = '670103', @Name = 'Thalassery';
EXEC AddLocation @Zipcode = '689501', @Name = 'Pandalam';
EXEC AddLocation @Zipcode = '671315', @Name = 'Kanhangad';
EXEC AddLocation @Zipcode = '686141', @Name = 'Vaikom';
EXEC AddLocation @Zipcode = '676306', @Name = 'Tirurangadi';
EXEC AddLocation @Zipcode = '695121', @Name = 'Neyyattinkara';
EXEC AddLocation @Zipcode = '679329', @Name = 'Nilambur';
EXEC AddLocation @Zipcode = '683572', @Name = 'Angamaly';
EXEC AddLocation @Zipcode = '685508', @Name = 'Kattappana';
EXEC AddLocation @Zipcode = '680664', @Name = 'Kodungallur';
EXEC AddLocation @Zipcode = '686662', @Name = 'Koothattukulam';
EXEC AddLocation @Zipcode = '680567', @Name = 'Thriprayar';
EXEC AddLocation @Zipcode = '671123', @Name = 'Kasargod';
EXEC AddLocation @Zipcode = '690518', @Name = 'Karunagappally';
EXEC AddLocation @Zipcode = '671202', @Name = 'Kanhangad, Hosdurg';
EXEC AddLocation @Zipcode = '670301', @Name = 'Payyannur, Kannur';
EXEC AddLocation @Zipcode = '679357', @Name = 'Mannarakkat, Palakkad';
EXEC AddLocation @Zipcode = '686123', @Name = 'Erattupetta, Kottayam';
EXEC AddLocation @Zipcode = '673004', @Name = 'Vellayil, Kozhikode';
EXEC AddLocation @Zipcode = '670562', @Name = 'Kannur University, Thalassery';
EXEC AddLocation @Zipcode = '673635', @Name = 'Vadakara, Kozhikode';
EXEC AddLocation @Zipcode = '695030', @Name = 'Kesavadasapuram, Thiruvananthapuram';
EXEC AddLocation @Zipcode = '678581', @Name = 'Alathur, Palakkad';
EXEC AddLocation @Zipcode = '673579', @Name = 'Koothuparamba, Kannur';
EXEC AddLocation @Zipcode = '680103', @Name = 'Puzhakkal, Thrissur';
EXEC AddLocation @Zipcode = '695035', @Name = 'Vellayambalam, Thiruvananthapuram';
EXEC AddLocation @Zipcode = '695006', @Name = 'Sreekariyam, Thiruvananthapuram';
EXEC AddLocation @Zipcode = '680025', @Name = 'Kuttanellur, Thrissur';
EXEC AddLocation @Zipcode = '670309', @Name = 'Peravoor, Kannur';
EXEC AddLocation @Zipcode = '682507', @Name = 'Edakochi, Ernakulam';
EXEC AddLocation @Zipcode = '686512', @Name = 'Vaikom, Kottayam';
EXEC AddLocation @Zipcode = '670106', @Name = 'Kadirur, Kannur';
EXEC AddLocation @Zipcode = '686575', @Name = 'Pala, Kottayam';
EXEC AddLocation @Zipcode = '676314', @Name = 'Changaramkulam, Malappuram';
EXEC AddLocation @Zipcode = '673613', @Name = 'Mukkam, Kozhikode';
EXEC AddLocation @Zipcode = '682032', @Name = 'Panampilly Nagar, Kochi';
EXEC AddLocation @Zipcode = '686001', @Name = 'Changanassery, Kottayam';
EXEC AddLocation @Zipcode = '680666', @Name = 'Edathiruthy, Thrissur';
EXEC AddLocation @Zipcode = '678555', @Name = 'Ottappalam, Palakkad';
EXEC AddLocation @Zipcode = '686105', @Name = 'Kanjirappally, Kottayam';
EXEC AddLocation @Zipcode = '680121', @Name = 'Irinjalakuda, Thrissur';
EXEC AddLocation @Zipcode = '679551', @Name = 'Edappal, Malappuram';
EXEC AddLocation @Zipcode = '676504', @Name = 'Nilambur, Malappuram';
EXEC AddLocation @Zipcode = '686002', @Name = 'Puthuppally, Kottayam';
EXEC AddLocation @Zipcode = '670007', @Name = 'Dharmasala, Kannur';
EXEC AddLocation @Zipcode = '670141', @Name = 'Taliparamba, Kannur';
EXEC AddLocation @Zipcode = '682018', @Name = 'Maradu, Kochi';
EXEC AddLocation @Zipcode = '686661', @Name = 'Muvattupuzha, Ernakulam';
EXEC AddLocation @Zipcode = '680564', @Name = 'Chalakudy, Thrissur';
EXEC AddLocation @Zipcode = '678104', @Name = 'Mannarkkad, Palakkad';
EXEC AddLocation @Zipcode = '673014', @Name = 'Calicut Beach, Kozhikode';
EXEC AddLocation @Zipcode = '682014', @Name = 'Vennala, Kochi';
EXEC AddLocation @Zipcode = '686001', @Name = 'Thirunakkara, Kottayam';
EXEC AddLocation @Zipcode = '689695', @Name = 'Chengannur, Alappuzha';
EXEC AddLocation @Zipcode = '676121', @Name = 'Manjeri, Malappuram';
EXEC AddLocation @Zipcode = '689108', @Name = 'Aranmula, Pathanamthitta';
EXEC AddLocation @Zipcode = '670307', @Name = 'Payyannur, Kannur';
EXEC AddLocation @Zipcode = '682014', @Name = 'Vennala, Kochi';
EXEC AddLocation @Zipcode = '678584', @Name = 'Ottappalam, Palakkad';
EXEC AddLocation @Zipcode = '673638', @Name = 'Kuttiady, Kozhikode';
EXEC AddLocation @Zipcode = '689641', @Name = 'Thiruvalla, Pathanamthitta';
EXEC AddLocation @Zipcode = '680667', @Name = 'Mala, Thrissur';
EXEC AddLocation @Zipcode = '686102', @Name = 'Karukachal, Kottayam';
EXEC AddLocation @Zipcode = '695014', @Name = 'Pappanamcode, Thiruvananthapuram';
EXEC AddLocation @Zipcode = '680007', @Name = 'Poothole, Thrissur';
EXEC AddLocation @Zipcode = '686001', @Name = 'Kottayam, Changanassery';
EXEC AddLocation @Zipcode = '673008', @Name = 'Vadakara, Kozhikode';
EXEC AddLocation @Zipcode = '695607', @Name = 'Kadinamkulam, Thiruvananthapuram';
EXEC AddLocation @Zipcode = '683514', @Name = 'Paravoor, Ernakulam';
EXEC AddLocation @Zipcode = '670001', @Name = 'Kannur, Taliparamba';
EXEC AddLocation @Zipcode = '683108', @Name = 'Tripunithura, Ernakulam';
EXEC AddLocation @Zipcode = '680001', @Name = 'Thrissur, Round West';
EXEC AddLocation @Zipcode = '682314', @Name = 'Thrippunithura, Kochi';
EXEC AddLocation @Zipcode = '695032', @Name = 'Kesavadasapuram, Thiruvananthapuram';
EXEC AddLocation @Zipcode = '689101', @Name = 'Thiruvalla, Mannadi';
EXEC AddLocation @Zipcode = '670706', @Name = 'Kunhimangalam, Kannur';
EXEC AddLocation @Zipcode = '676505', @Name = 'Malappuram, Thalakkad';
EXEC AddLocation @Zipcode = '683572', @Name = 'Angamaly, AIMS Kochi';
EXEC AddLocation @Zipcode = '673634', @Name = 'Vadakara, Kozhikode';
EXEC AddLocation @Zipcode = '673614', @Name = 'Mukkam, Kozhikode';
EXEC AddLocation @Zipcode = '686674', @Name = 'Kanjar, Kottayam';
EXEC AddLocation @Zipcode = '670306', @Name = 'Payyannur, Kannur';
EXEC AddLocation @Zipcode = '695002', @Name = 'Thiruvananthapuram, Statue';
EXEC AddLocation @Zipcode = '670645', @Name = 'Kadirur, Kannur';
EXEC AddLocation @Zipcode = '673575', @Name = 'Edachery, Kozhikode';
EXEC AddLocation @Zipcode = '686563', @Name = 'Koothattukulam, Ernakulam';
EXEC AddLocation @Zipcode = '679513', @Name = 'Edavanakkad, Malappuram';
EXEC AddLocation @Zipcode = '682017', @Name = 'Thevara, Kochi';
EXEC AddLocation @Zipcode = '695042', @Name = 'Muttada, Thiruvananthapuram';
EXEC AddLocation @Zipcode = '683501', @Name = 'North Paravur, Ernakulam';
EXEC AddLocation @Zipcode = '676122', @Name = 'Valanchery, Malappuram';
EXEC AddLocation @Zipcode = '670105', @Name = 'Chokli, Kannur';
EXEC AddLocation @Zipcode = '689661', @Name = 'Pandalam, Pathanamthitta';
EXEC AddLocation @Zipcode = '676122', @Name = 'Valanchery, Malappuram';
EXEC AddLocation @Zipcode = '670105', @Name = 'Chokli, Kannur';
EXEC AddLocation @Zipcode = '689661', @Name = 'Pandalam, Pathanamthitta';
EXEC AddLocation @Zipcode = '673655', @Name = 'Chaliyam, Kozhikode';
EXEC AddLocation @Zipcode = '683587', @Name = 'Cherai, Ernakulam';
EXEC AddLocation @Zipcode = '671551', @Name = 'Manjeswaram, Kasaragod';
EXEC AddLocation @Zipcode = '686575', @Name = 'Ramapuram, Kottayam';
EXEC AddLocation @Zipcode = '680682', @Name = 'Mupliyam, Thrissur';
EXEC AddLocation @Zipcode = '676123', @Name = 'Manjeri, Malappuram';
EXEC AddLocation @Zipcode = '680021', @Name = 'Thrissur, Chelakottukara';
EXEC AddLocation @Zipcode = '676122', @Name = 'Valanchery, Malappuram';
EXEC AddLocation @Zipcode = '670105', @Name = 'Chokli, Kannur';
EXEC AddLocation @Zipcode = '689661', @Name = 'Pandalam, Pathanamthitta';
EXEC AddLocation @Zipcode = '673655', @Name = 'Chaliyam, Kozhikode';
EXEC AddLocation @Zipcode = '683587', @Name = 'Cherai, Ernakulam';
EXEC AddLocation @Zipcode = '671551', @Name = 'Manjeswaram, Kasaragod';
EXEC AddLocation @Zipcode = '686575', @Name = 'Ramapuram, Kottayam';
EXEC AddLocation @Zipcode = '680682', @Name = 'Mupliyam, Thrissur';
EXEC AddLocation @Zipcode = '676123', @Name = 'Manjeri, Malappuram';
EXEC AddLocation @Zipcode = '680021', @Name = 'Thrissur, Chelakottukara';
EXEC AddLocation @Zipcode = '686014', @Name = 'Changanassery, Kottayam';
EXEC AddLocation @Zipcode = '673308', @Name = 'Balusseri, Kozhikode';
EXEC AddLocation @Zipcode = '689691', @Name = 'Kulakkada, Pathanamthitta';
EXEC AddLocation @Zipcode = '673017', @Name = 'Kozhikode, Arayidathupetta';
--140 locations
SELECT * FROM MovieMate.Location